drop user ENDCY cascade;
drop tablespace KD_ENDCY_TBS including contents and datafiles cascade constraints;

--建表空间
CREATE TABLESPACE KD_ENDCY_TBS
    LOGGING
    DATAFILE 'KD_ENDCY_TBS.DBF' SIZE 100M REUSE
    AUTOEXTEND
    ON NEXT 10M EXTENT MANAGEMENT LOCAL SEGMENT
    SPACE MANAGEMENT  AUTO;

--建用户
CREATE USER ENDCY
  IDENTIFIED by "1"
  DEFAULT TABLESPACE KD_ENDCY_TBS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT;
GRANT CONNECT,SELECT_CATALOG_ROLE TO ENDCY;
GRANT
      CREATE CLUSTER,
      CREATE INDEXTYPE,
      CREATE OPERATOR,
      CREATE PROCEDURE,
      CREATE SEQUENCE,
      CREATE SESSION,
      CREATE TABLE,
      CREATE TRIGGER,
      CREATE TYPE,
      CREATE VIEW,
      CREATE USER
TO ENDCY;
GRANT
      CREATE ANY INDEX,
      CREATE ANY PROCEDURE,
      CREATE ANY SYNONYM,
      CREATE ANY VIEW,
      CREATE ANY TABLE,
      CREATE PUBLIC SYNONYM
TO ENDCY;
GRANT
   ALTER ANY INDEX,
   ALTER ANY TABLE,
   ALTER USER
TO ENDCY;
GRANT
   DELETE ANY TABLE,
   DROP ANY TABLE,
   DROP ANY VIEW,
   DROP USER,
   INSERT ANY TABLE,
   SELECT ANY DICTIONARY,
   SELECT ANY TABLE,
   UPDATE ANY TABLE,
   GRANT ANY OBJECT PRIVILEGE
TO ENDCY;
GRANT CREATE DATABASE LINK TO ENDCY;
ALTER USER ENDCY QUOTA UNLIMITED ON KD_ENDCY_TBS;
